### ISSUE TITLE
BPM Tools: readout shows BPM/2

### ISSUE THREAD

**Issue by phdsg** [martin-lueders/ML_modules#25]
OS: win
Rack: dev
Plugin: dev

input on the module is JW clock set to 60bpm.
readout on bpmtools shows 30.0.

**Comment by martin-lueders** [comment]
Do you have a new version of JW clock? Mine does not show any bpm value...

**Comment by phdsg** [comment]
no, jw doesn't have a readout (yet. requested one).
do you want to know how i checked that it's actually 60?
i wanted to set up a stop-watch using 2 of your counters (one for seconds one for minutes) and a clock.
setting the clock manually using your bpm analyzer to 60bpm made the "seconds-counter" tick twice every second.

**Comment by martin-lueders** [comment]
I think you are fooled by some missed beats, which can happen if some signal paths have a 1 module delay while others are direct.

You can do two tests you can do: If you set the speed of 60 bpm you should get 1 beat per second, which is easy to check. You can also put it after Autodafe's BPM clock, and see that you get a consistent results.

**Comment by phdsg** [comment]
i'll do some more checks...

**Comment by phdsg** [comment]
here's how it looks with autodafe clock set up to sync the counter with realtime seconds.
![bpmtools2](https://user-images.githubusercontent.com/33329578/33229951-b7af0f22-d1d9-11e7-99c2-fce2733d29ce.PNG)

**Comment by phdsg** [comment]
oh my, that is weird...
i checked again with a soundgenerator so i'm not fooled by my eyes and
low and behold, all numbers are good.

can be closed i guess as it's only happening with no core/audiodevice

**Comment by martin-lueders** [comment]
OK. I just checked against luckyxxx again.

I guess the confusing thing is that they work differently.
While Autodafe's BPM clock gives one tick per beat, meaning the '1' output gives 2 beats per second at 120 bpm, the lucky one gives it relative to 'bars', not beats' His plugin gives a tick only at the beginning of a bar (4 beats) at the '1/1' output, and you need the '1/4' output to get a tick per beat.

Unfortunately, both could be abbreviated with BMP: "beats per minute" or "bars per minute".

But is looks my BPM tool (and I refer to BEATS per minute) works fine.
It should not have anything to do with core or audiodevices attaches.

The problem in your first post might be related to the fact I explained, that you could loose the first beet in the counter if the pulse on "Start" comes one sample delayed (which would happen due to the inserted UTILITY modules. Try to insert a MULTIPLY or something else in the other signal path as well.

Hope that helps.
Martin

**Comment by phdsg** [comment]
although this is not an issue anymore,
you can check what i meant with the audio-device using this setup.

![bpmtools4](https://user-images.githubusercontent.com/33329578/33231430-b918a9ec-d1f5-11e7-8cd8-73031d154183.PNG)

with audio device selected the system behaves correctly. 1 tick per second.
with no audio device selected it ticks faster.
